CREATE DATABASE SCSU;
USE SCSU;

CREATE TABLE USERS
(
	USER_ID			INT				NOT NULL	AUTO_INCREMENT,
	FIRST_NAME		VARCHAR(20)			NOT NULL,
	LAST_NAME		VARCHAR(20)			NOT NULL,					 
	EMAIL			VARCHAR(35)			NOT NULL,
	PASS_HASH		VARCHAR(250)			NOT NULL,
	isBANNED		BOOLEAN	,
	EMAIL_CONFIRM		BOOLEAN,
	CONFIRM_TIME		DATETIME,
	USER_BIO		VARCHAR(800),
	BIRTH_DATE		DATETIME,
	isADMIN			BOOLEAN, 
	AVATAR			blob,
	MAJOR			VARCHAR(10)			NOT NULL,
	PRIMARY KEY (USER_ID)
);

CREATE TABLE EVENTS
(
	EVENT_ID		INT				NOT NULL	AUTO_INCREMENT,
	EVENT_NAME		VARCHAR(50)			NOT NULL,
	LOCATION		VARCHAR(50)			NOT NULL,
	START_TIME		DATETIME			NOT NULL,
	END_TIME		DATETIME			NOT NULL,
	CREATOR_ID		INT				NOT NULL,
	DESCRIPTION		VARCHAR(800),
	MAX			INT,
	PRIVATE			TINYINT,
	GROUP_ID		INT,
	PRIMARY KEY (EVENT_ID),
	FOREIGN KEY (CREATOR_ID) REFERENCES USERS(USER_ID)  
);

CREATE TABLE COMMENTS
(
	COMMENT_ID		INT					NOT NULL,
	COMMENT			TINYTEXT				NOT NULL,
	POST_FNAME		VARCHAR(30)				NOT NULL,
	POST_LNAME		VARCHAR(30)				NOT NULL,
	COMMENT_TIME		DATETIME				NOT NULL,
	FOREIGN KEY COMMENT_ID REFERENCES EVENTS(EVENT_ID),
);

CREATE TABLE COMMENTS_GROUPS
(
	COMMENT_ID		INT					NOT NULL,
	COMMENT			TINYTEXT				NOT NULL,
	POST_FNAME		VARCHAR(30)				NOT NULL,
	POST_LNAME		VARCHAR(30)				NOT NULL,
	COMMENT_TIME		DATETIME				NOT NULL,
	FOREIGN KEY COMMENT_ID REFERENCES GROUPS(GROUP_ID),
);

CREATE TABLE TAGS
( 
	TAG_ID			INT				NOT NULL	AUTO_INCREMENT,
	TAG_TITLE		VARCHAR(20)			NOT NULL,
	isPRIMARY		BOOLEAN				NOT NULL
);

CREATE TABLE EVENT_TAGS
(
	EVENT_ID		INT					NOT NULL,
	TAG_ID			INT					NOT NULL,
	CONSTRAINT (EVENT_TAG) PRIMARY KEY (EVENT_ID, TAG_ID),
	FOREIGN KEY(EVENT_ID) REFERENCES EVENT(EVENT_ID),
	FOREIGN KEY(TAG_ID) REFERENCES TAGS(TAG_ID)
);


CREATE TABLE GROUPS
(
	GROUP_ID		INT					NOT NULL	AUTO_INCREMENT,
	GROUP_NAME		VARCHAR(50)				NOT NULL,
	GROUP_OWNER_ID		INT					NOT NULL,
	GROUP_DESCRIPTION	VARCHAR(800),
	PRIVATE_GROUP		BIT,
	FOREIGN KEY(GROUP_OWNER) REFERENCES USERS(USER_ID)

);

CREATE TABLE GROUP_TAGS
(
	GROUP_ID		INT					NOT NULL,
	TAG_ID			INT					NOT NULL,
	CONSTRAINT (GROUP_TAG) PRIMARY KEY (GROUP_ID, TAG_ID),
	FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(GROUP_ID),
	FOREIGN KEY(TAG_ID) REFERENCES TAGS(TAG_ID)
);

CREATE TABLE GROUP_MEMBERS
(
	GROUP_ID		INT					NOT NULL,
	MEMBER_ID		INT					NOT NULL,
	CONSTRAINT (GROUP_MEMBER) PRIMARY KEY(GROUP_ID, MEMBER_ID),
	FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(GROUP_ID),
	FOREIGN KEY(MEMBER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE EVENT_ATTENDEES
(
	EVENT_ID		INT					NOT NULL,
	ATTENDEE_ID		INT					NOT NULL,
	CONSTRAINT (EVENT_ATTENDEE) PRIMARY KEY (EVENT_ID, ATTENDEE_ID),
	FOREIGN KEY(EVENT_ID) REFERENCES EVENTS(EVENT_ID).
	FOREIGN KEY(ATTENDEE_ID) REFERENCES USERS(USER_ID)
);
